---
name: Minsoek
surname: Choi
position: "Student"
address: "School of finance"
phone: +1 10 2261 2053
www: Minseok.com
email: "justin3111@naver.com"
twitter: x
github: alstjr231
linkedin: x
date: "`r format(Sys.time(), '%B %Y')`"
output:
  vitae::awesomecv:
    page_total: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```

# Some stuff about me

 * 6month experience of Research at Samsung securities.
 * Member of HYFE
 * CFA research challenge winner.

# Education

```{r}
library(tibble)
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where,
  "Informal studies", "2016-23", "HanyangUniversity", "Seoul, Korea", 

) %>%
  detailed_entries(Degree, Year, Institution, Where)
```

# 

```{r}
tribble(
  ~Year, ~Type, ~Desc,
  1903, "Physics", "Awarded for her work on radioactivity with Pierre Man and Henri Becquerel",
  1911, "Chemistry", "Awarded for the discovery of radium and polonium"
) %>%
  brief_entries(
    glue::glue("Nobel Prize in {Type}"),
    Year,
    Desc
  )
```

# Publications

```{r}
library(dplyr)
knitr::write_bib(c("vitae", "tibble"), "packages.bib")

bibliography_entries("packages.bib") %>%
  arrange(desc(author$family), issued)
```
